name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to improve?
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Why is it useful?
    validations:
      required: true
